#!/bin/bash

set -eu

export GOPATH=$PWD/gopath
export PATH=$PWD/gopath/bin:$PATH

cd copy-pasta

echo "installing ginkgo..."
go get github.com/onsi/ginkgo/ginkgo
go get github.com/onsi/gemega/...

echo "$GOPATH"
echo "running tests..."
go test ./...
