#!/bin/bash

set -eu

export GOPATH=$PWD/gopath
export PATH=$PWD/gopath/bin:$PATH

cd copy-pasta

 echo "installing ginkgo..."
 go install github.com/onsi/ginkgo/ginkgo

echo "$GOPATH"
echo "running tests..."
ginkgo -r
